Repository Cog-Creators/Red-Index, pull requests merged in 2023-05, with the labels that each got.

#88 Include friendly repo name in cache dir name
  indexer.py
  parser.py
Labels: Type: Index enhancement

#89 Rename bz_cogs repo
  repositories.yaml
Labels: Repository type: unapproved, Type: Repository list change

#90 Add BotC-Red-Cogs
  repositories.yaml
Labels: Type: Repository list add, Repository type: unapproved
