Repository Cog-Creators/Red-Index, pull requests merged in 2023-06, with the labels that each got.

#91 Delist cogs w/o 3.5 changes
  repositories.yaml
Labels: Repository type: unapproved, Repository type: approved, Type: Repository list change

#95 Re-add Pokecord to unapproved after 3.5 support
  repositories.yaml
Labels: Type: Repository list add, Repository type: unapproved

#97 Re-add Fox-V3 after update
  repositories.yaml
Labels: Repository type: approved, Type: Repository list change

#98 Add aaa3a to approved list
  repositories.yaml
Labels: Repository type: approved, Type: Repository list change

#99 Add maxcogs to approved list
  repositories.yaml
Labels: Repository type: approved, Type: Repository list change

#101 Add Valors-cogs to unapproved repo list
  repositories.yaml
Labels: Type: Repository list add, Repository type: unapproved

#103 Restore CogsByAdrian to the index
  repositories.yaml
Labels: Repository type: approved, Type: Repository list change
