Repository Cog-Creators/Red-Index, pull requests merged in 2024-03, with the labels that each got.

#127 Rename BackRoomCogs to ShitShowCogs
  repositories.yaml
Labels: Repository type: unapproved, Type: Repository list change

#126 Add CCCogs to unapproved
  repositories.yaml
Labels: Type: Repository list add, Repository type: unapproved

#128 Swap sravan-cogs to approved
  repositories.yaml
Labels: Repository type: approved, Type: Repository list change

#129 add ben-cogs to unapproved
  repositories.yaml
Labels: Type: Repository list add, Repository type: unapproved
