Repository Cog-Creators/Red-Index, pull requests merged in 2025-03, with the labels that each got.

#148 Add RedBot-Cogs to approved repositories
  repositories.yaml
Labels: Type: Repository list add, Repository type: approved

#150 Rename RedBot-Cogs to Reediculous-Cogs
  repositories.yaml
Labels: Repository type: approved, Type: Repository list change

#149 Updating repo destination
  repositories.yaml
Labels: Repository type: unapproved, Type: Repository list change

#151 Added Prime-Cogs
  repositories.yaml
Labels: Type: Repository list add, Repository type: unapproved

#152 Remove ShitShowCogs from unapproved
  repositories.yaml
Labels: Repository type: unapproved, Type: Repository list remove
